.\" ========================
.\" =====    ===============
.\" ======  ================
.\" ======  ================
.\" ======  ====   ====   ==
.\" ======  ===     ==  =  =
.\" ======  ===  =  ==     =
.\" =  ===  ===  =  ==  ====
.\" =  ===  ===  =  ==  =  =
.\" ==     =====   ====   ==
.\" ========================
.\"
.\" SPDX-License-Identifier: BSD-3-Clause
.\"
.\" Copyright (c) 2020 Joe
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the organization nor the
.\"    names of its contributors may be used to endorse or promote products
.\"    derived from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY JOE ''AS IS'' AND ANY
.\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL JOE BE LIABLE FOR ANY
.\" DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
.\" LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" unixize: man/unixize.1
.\" 2020-11-14 20:57
.\" date
.\" Joe
.\"
.\" Manpage for unixize.
.\" Contact rbousset@42lyon.fr to correct errors and typos.
.\"
.de Text
.nop \)\\$*
..
.de squoted_text
.Text \\$3\(oq\fB\\$1\f[]\(cq\\$2
..
.de dquoted_text
.Text \\$3\(lq\fB\\$1\f[]\(rq\\$2
..
.de file_example
.P
.RS
\`\\$1\' \-\> \`\\$2\'
.RE
.P
..
.
.
.TH unixize 1 "15 November 2020" "unixize 1.0"
.
.
.SH NAME
.B unixize
\- bulk rename directory
.
.
.SH SYNOPSIS
.SY unixize
.RB [ \-ahiknprRv ]
[\c
.BI \-e ext\c
]
.I directory
.YS
.
.
.SH DESCRIPTION
.P
The
.B unixize
utility renames all file in a given
.I directory
to a predefined style. Here is a description of the
.B unixize
behaviour without options. This behavious can be changed using options, see
\(lqOPTIONS\(rq below. By default:
.
.P
.
All upper-case characters will be set to lower-case.
.
.file_example "FILE" "file"
.
Spaces will be substitued by a
.BR separator ,
by default underscores
.squoted_text _ ) (
.
.file_example "a file with spaces.org" "a_file_with_spaces.org"
.
Multiple spaces will be condensed into only one
.BR sparator .
.
.file_example "lots      of     spaces.gif" "lots_of_spaces.gif"
.
All unicode characters will be deleted
except for latin extended ascii characters, which will be replaced by the most
relevant ascii character (or double characters).
.
.file_example "\(Eu\-Hliðskjálf-\(de\(dd.jpg" "hlidhskjalf.jpg"
.
.SH OPTIONS
.SH SEE ALSO
.IR ascii (1),
.IR rename (2)
.\" vim: set filetype=groff:
